# Generated by Django 3.2.8 on 2021-12-03 20:37

import ckeditor_uploader.fields
import core.models.authors
import core.models.files
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=254, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Tipo de acesso',
                'verbose_name_plural': 'Tipos de acesso',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='avatar.png', upload_to=core.models.authors.get_file_path, verbose_name='Avatar')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo')),
                ('slug', models.SlugField(blank=True, max_length=254, null=True, unique=True, verbose_name='Slug')),
                ('about', models.TextField(blank=True, max_length=500, null=True, verbose_name='Sobre o Autor')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkedin')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('github', models.CharField(blank=True, max_length=255, null=True, verbose_name='Github')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=254, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=254, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Área de conhecimento',
                'verbose_name_plural': 'Áreas de conhecimento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=254, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=254, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Tipo de publicação',
                'verbose_name_plural': 'Tipos de publicação',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sub-título')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Conteúdo')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Excerto')),
                ('publish', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('first_advisor', models.CharField(blank=True, max_length=255, verbose_name='Primeiro orientador(a)')),
                ('second_advisor', models.CharField(blank=True, max_length=255, verbose_name='Segundo orientador(a)')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Palavras-chave')),
                ('cnpq', models.CharField(blank=True, max_length=255, null=True, verbose_name='CNPq')),
                ('language', models.CharField(blank=True, max_length=100, null=True, verbose_name='Idioma')),
                ('country', models.CharField(blank=True, default='Brasil', max_length=100, null=True, verbose_name='Pais')),
                ('editor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Editor')),
                ('initials_institution', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sigla instituição')),
                ('quote', models.TextField(blank=True, null=True, verbose_name='Citação')),
                ('date_document', models.DateTimeField(blank=True, null=True, verbose_name='Data do documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('author', models.ManyToManyField(blank=True, related_name='publication_author', to='core.Author', verbose_name='Autor(es)')),
                ('categories', models.ManyToManyField(blank=True, related_name='publication_categories', to='core.Category', verbose_name='Categorias')),
                ('knowledge_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_knowledge', to='core.knowledge', verbose_name='Área de conhecimento')),
                ('tags', models.ManyToManyField(blank=True, related_name='publication_tag', to='core.Tag', verbose_name='Tags')),
                ('type_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_access', to='core.access', verbose_name='Tipo de acesso')),
                ('type_publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_type', to='core.type', verbose_name='Tipo de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('file', models.FileField(null=True, upload_to=core.models.files.get_file_path, verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.publication', verbose_name='Publicação')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
    ]
